INSERT INTO PERSON (ID, NAME, LOCATION)
VALUES(10001,  'Ranga', 'Hyderabad');
INSERT INTO PERSON (ID, NAME, LOCATION)
VALUES(10002,  'James', 'New York');
INSERT INTO PERSON (ID, NAME, LOCATION)
VALUES(10003,  'Pieter', 'Amsterdam');